### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by TonySky1228** [denikson/COM3D2.MaidFiddler#16]
**Error message**
Paste the error message in the area below:
```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 125, in maid_selected
  File "maidfiddler\ui\tabs\maid_stats.py", line 146, in on_maid_selected
  File "maidfiddler\ui\qt_elements.py", line 24, in set_value
TypeError: setText(self, str): argument 1 has unexpected type 'bool'

```

**To Reproduce**
Happened connecting to the game
**Version information:**
 - Game version 1.31
 - Maid Fiddler version 1.0.4.4

**Additional context**
Add any other context about the problem here if there is any.

**Comment by denikson** [comment]
Old issue, closing. Maid Fiddler has since been updated and the game as well. Please make sure your Maid Fiddler and game are up-to-date.

Please create a new issue if the problem still persists.
