### ISSUE TITLE
HELP!!

### ISSUE THREAD

**Issue by CRAZY-PIG61** [denikson/COM3D2.MaidFiddler#22]
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 125, in maid_selected
  File "maidfiddler\ui\tabs\maid_stats.py", line 146, in on_maid_selected
  File "maidfiddler\ui\qt_elements.py", line 24, in set_value
TypeError: setText(self, str): argument 1 has unexpected type 'bool'

**Comment by denikson** [comment]
Old issue, closing. Maid Fiddler has since been updated and the game as well. Please make sure your Maid Fiddler and game are up-to-date.

Please create a new issue if the problem still persists.
