### ISSUE TITLE
Maid Fiddler closes after finding game

### ISSUE THREAD

**Issue by harouki** [denikson/COM3D2.MaidFiddler#23]
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 131, in maid_selected
  File "maidfiddler\ui\tabs\maid_info.py", line 205, in on_maid_selected
KeyError: 'mainChara'

**Comment by denikson** [comment]
Old issue, closing. Maid Fiddler has since been updated and the game as well.

Please create a new issue if the problem still persists.
