### ISSUE TITLE
mainChara Error

### ISSUE THREAD

**Issue by geesoo** [denikson/COM3D2.MaidFiddler#26]
**Error message**
Paste the error message in the area below:
```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 131, in maid_selected
  File "maidfiddler\ui\tabs\maid_info.py", line 205, in on_maid_selected
KeyError: 'mainChara'
```

**Version information:**
 - Game version [1.38]
 - Maid Fiddler version [1.06]

**Comment by denikson** [comment]
Old issue, closing. Maid Fiddler has since been updated and the game as well.

Please create a new issue if the problem still persists.
