### ISSUE TITLE
Maid fiddler continually crashes and asks for a restart after loading game

### ISSUE THREAD

**Issue by contown** [denikson/COM3D2.MaidFiddler#30]
Maid fiddler stops working every time I pull up my [save.](https://imgur.com/a/uhj3aIz)
```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 116, in maid_selected
  File "maidfiddler\util\pipes.py", line 109, in <lambda>
  File "maidfiddler\util\pipes.py", line 56, in __call__
  File "maidfiddler\util\pipes.py", line 103, in try_invoke
maidfiddler.util.pipes.RemoteError: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Service.Service.ReadMaidData (.Maid maid) [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Service.Service.SelectActiveMaid (System.String guid) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

****
I just opened up my  save and saw my maids on the side, then suddenly that error popped up and I was told to restart maid fiddler. Restarting didn't do anything.

**Version information:**
I'm running on the most recent version of COM3D2 (1.04.1) and the most recent version of maid fiddler. (1.0.7)

**Comment by denikson** [comment]
Gave this a test on Maid Fiddler 1.0.7.0 and COM 1.04.2 and it works fine:

![image](https://user-images.githubusercontent.com/13762037/77459508-7e8a2d80-6e08-11ea-955d-b2d1e964c908.png)

As such, make sure that

* You have latest version of Maid Fiddler installed (latest is 1.0.7.0, not 1.0.6.0)
* You indeed have the latest game version (you can check so via the game)
* You have either latest Sybaris or BepInEx and you have them properly installed
* You actually installed Maid Fiddler in the correct folder (i.e. you actually installed it where your English version of the game is located)

Closing this issue as I cannot replicate it. If you still have problems, please create a new issue.
