### ISSUE TITLE
Steam Version Error

### ISSUE THREAD

**Issue by IDunno1337** [denikson/COM3D2.MaidFiddler#31]
**Error message**
Paste the error message in the area below:
```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 120, in maid_selected
  File "maidfiddler\util\pipes.py", line 123, in <lambda>
  File "maidfiddler\util\pipes.py", line 59, in __call__
  File "maidfiddler\util\pipes.py", line 65, in try_invoke
  File "maidfiddler\util\pipes.py", line 117, in _try_invoke_internal
maidfiddler.util.pipes.RemoteError: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Service.Service.ReadMaidData (.Maid maid) [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Service.Service.SelectActiveMaid (System.String guid) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 

```

**To Reproduce**
Updated Steam ver from COM3D2's website to most recent ver and attempted to run Maid Fiddler. Clicking anything gets the error message above.
**Version information:**
 - Game version [1.042]
 - Maid Fiddler version [1.0.6.0]

**Additional context**

**Comment by ChaosSonic1** [comment]
I been having the same problem

**Comment by denikson** [comment]
Gave this a test on Maid Fiddler 1.0.7.0 and COM 1.04.2 and it works fine:

![image](https://user-images.githubusercontent.com/13762037/77459508-7e8a2d80-6e08-11ea-955d-b2d1e964c908.png)

As such, make sure that

* You have latest version of Maid Fiddler installed (latest is 1.0.7.0, not 1.0.6.0)
* You indeed have the latest game version (you can check so via the game)
* You have either latest Sybaris or BepInEx and you have them properly installed
* You actually installed Maid Fiddler in the correct folder (i.e. you actually installed it where your English version of the game is located)

Closing this issue as I cannot replicate it. If you still have problems, please create a new issue.
