### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by jack15-5** [denikson/COM3D2.MaidFiddler#4]
**Error message**
Paste the error message in the area below:
```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 114, in maid_selected
  File "maidfiddler\util\pipes.py", line 109, in <lambda>
  File "maidfiddler\util\pipes.py", line 56, in __call__
  File "maidfiddler\util\pipes.py", line 103, in try_invoke
maidfiddler.util.pipes.RemoteError: System.FieldAccessException: Field `MaidStatus.Status:bonusStatus' is inaccessible from method `COM3D2.MaidFiddler.Core.Service.Service:ReadMaidData (Maid)'

  at COM3D2.MaidFiddler.Core.Service.Service.SelectActiveMaid (System.String guid) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

**To Reproduce**
Write a small description of what you tried to do (in GUI or the game).

After launching the game, we loaded saved data and started the program, but when I clicked the screen, an error log appeared.

**Version information:**
 - Game version [e.g. 1.191]
 - Maid Fiddler version [Version 1.0.0.0]

**Additional context**
Add any other context about the problem here if there is any.

**Comment by denikson** [comment]
Thank you for the report!

Do you have `Mono.Cecil.Inject.dll` in your `Sybaris` folder?

**Comment by jack15-5** [comment]
Thank you for your reply.

I did not introduce that file.
I just introduced it, it started normally.

Thank you very much!

**Comment by denikson** [comment]
Thank you for the information!

I will add the file into the next version of Maid Fiddler so this will not happen again.

Sorry for any inconvenience!
