### ISSUE TITLE
Maid Fiddler crash after connecting

### ISSUE THREAD

**Issue by mirkone1994** [denikson/COM3D2.MaidFiddler#58]
**Error message**
```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 120, in maid_selected
  File "maidfiddler\util\pipes.py", line 124, in <lambda>
  File "maidfiddler\util\pipes.py", line 60, in __call__
  File "maidfiddler\util\pipes.py", line 66, in try_invoke
  File "maidfiddler\util\pipes.py", line 118, in _try_invoke_internal
maidfiddler.util.pipes.RemoteError: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Service.Service.ReadMaidData (.Maid maid) [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Service.Service+<>c__DisplayClass66_0.<SelectActiveMaid>b__0 () [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Utils.ExecutorHelper+<>c__DisplayClass3_0.<RunSync>b__0 () [0x00000] in <filename unknown>:0 
```

**To Reproduce**
Opening Sybaris 2.2, I move Sybaris/UnityInjector to Sybaris/Plugins
Start the game and load save
Go to Maid Edit
Start Maid Fiddler
Error message

**Version information:**
 - Game version [1.54.1]
 - Maid Fiddler version [1.0.8.2]

**Additional context**
I'm playing in the Steam version and updated from 1.0.8.1 to 1.54.1, than installed Truth's Sybaris 2.2 AIO package, than installed Maid Fiddler from the setup, version 1.0.8.2. Also moved the folder Sybaris/UnityInjector to Sybaris/Plugins, otherwise the GUi won't connect to the game.

**Comment by AmiyaRhodes** [comment]
请问您解决了吗？我也是这个问题
