### ISSUE TITLE
Crashing error with Scout maids

### ISSUE THREAD

**Issue by Antivash** [denikson/COM3D2.MaidFiddler#62]
**Error message**
Paste the error message in the area below:
```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 131, in maid_selected
  File "maidfiddler\ui\tabs\maid_stats.py", line 160, in on_maid_selected
KeyError: 'employmentDay'

```

**To Reproduce**
1: Create Scout Maid
2: Click to select maid in GUI to do anything within Maid Fiddler

**Version information:**
 - Game version: 1.54
 - Maid Fiddler: 1.0.8.2

**Additional context**
I was able to select the maid while I was in the editor when creating her, but once I exited, if I try to select her, I get the above error.

**Comment by HiCalvert** [comment]
what is that mean? Is there any example?

**Comment by AmiyaRhodes** [comment]
请问您解决了吗？我也是这个问题
