### ISSUE TITLE
GUI Traceback Error

### ISSUE THREAD

**Issue by 240Nerd** [denikson/COM3D2.MaidFiddler#65]
**Error message**
Paste the error message in the area below:
```
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 120, in maid_selected
  File "maidfiddler\util\pipes.py", line 124, in <lambda>
  File "maidfiddler\util\pipes.py", line 60, in __call__
  File "maidfiddler\util\pipes.py", line 66, in try_invoke
  File "maidfiddler\util\pipes.py", line 118, in _try_invoke_internal
maidfiddler.util.pipes.RemoteError: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Service.Service.ReadMaidData (.Maid maid) [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Service.Service+<>c__DisplayClass66_0.<SelectActiveMaid>b__0 () [0x00000] in <filename unknown>:0 
  at COM3D2.MaidFiddler.Core.Utils.ExecutorHelper+<>c__DisplayClass3_0.<RunSync>b__0 () [0x00000] in <filename unknown>:0 

```

**To Reproduce**
I have put my MaidFiddler.core into Sybris's plugin folder to get MaidFiddler to pick the game up (Path looks like "COM3D2>Sybris>Plugins>Unityinjector") and it now pick the game up but gives me the error above. Other than moving the .core I havent moved anything and left everything where the installer wanted them.

**Version information:**
 - Game version 1.55
 - Maid Fiddler version 1.0.8.2

**Additional context**
I am using the JP version

**Comment by tenwingtw2020** [comment]
Traceback (most recent call last):
  File "maidfiddler\ui\main_window.py", line 265, in on_connection_close
  File "maidfiddler\ui\main_window.py", line 169, in connect
  File "maidfiddler\ui\tabs\player.py", line 105, in reload_player_props
TypeError: 'NoneType' object is not subscriptable


Game version 1.55
Maid Fiddler version 1.0.8.2

**Comment by 240Nerd** [comment]
Updating Sybris fixed the issue
