### ISSUE TITLE
Maidfiddler crash on startup

### ISSUE THREAD

**Issue by twilight135246** [denikson/COM3D2.MaidFiddler#81]
Traceback (most recent call last):
  File "maidfiddler\ui\maids_list.py", line 131, in maid_selected
  File "maidfiddler\ui\tabs\maid_stats.py", line 147, in on_maid_selected
  File "maidfiddler\ui\qt_elements.py", line 24, in set_value
TypeError: setText(self, str): argument 1 has unexpected type 'bool'

**Comment by AmiyaRhodes** [comment]
请问您解决了吗，我也是这个问题
